config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chat_rooms, only: [:new,:create,:show,:index]
  resources :main, only: [:index]
  root to: "main#main"
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

  def timestamp
   created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:main]
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = "Chat room added!"    
      redirect_to chat_rooms_path
    else
      render :new
    end
  end

  def show 
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private
  
    def chat_room_params
      params.require(:chat_room).permit(:title)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def main
    render :main, :layout => false
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}",chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">	
			<h1>Chat rooms</h1>

			<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: "btn btn-primary" %></p>

			<ul>
				<%= render @chat_rooms %>
			</ul>
		</div>
	</div>
</div>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, autofocus: true, class: "form-control" %>
	</div>

	<%= f.submit "Add!", class: "btn btn-primary" %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
	<%= render @chat_room.messages %>
</div>

<%= form_for @message, url: '#' do |f| %>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: 'form-control' %>
		<small class="text-muted">From 2 to 1000 characters</small>
	</div>
	<%= f.submit "Post", class: "btn  btn-primary btn-lg" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChattingRoom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "shared/header" %>
    <%= render "shared/main" %>
    <%= yield %>
  </body>
</html>

app/views/main/main.html.erb
<!DOCTYPE html>
<html>
	<head>
		<!-- Required meta tags always come first -->
		<meta charset="UTF-8">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">

		<!-- Custom CSS -->
		<link rel="stylesheet" href="style.css">
		<title>Document</title>
	</head>
	<body>
		
		<section id="cover">
			<div id="cover-caption">
				<div class="container">
					<div class="col-sm-10 col-sm-offset-1">
						<h1>Welcome to Bootstrap</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga voluptate earum voluptatum ad hic at aut! Minus sunt, nemo! Error repellat nisi quod nam consectetur praesentium temporibus velit voluptatem maiores.</p>
						<form action="" class="form-inline">
							<button type="submit" class="btn btn-success ">okay, go!</button>
						</form>
						<br>
					</div>
				</div>
			</div>
		</section>

		<nav class="navbar navbar-dark navbar-fixed-bottom navbar-full" id="nav-main">
		  <div class="container">
		    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
		  </div>
		</nav>


		<!-- jquery first then Bootstrap JS -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	</body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.user.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="/">Logo</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item nav-link">Signed in as <%= current_user.name %></li>
      <li class="nav-item"><%= link_to "Signout", destroy_user_session_path, class: "btn btn-primary pull-right", method: :delete %></li>
    <% else %>
      <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary pull-right" %></li>
      <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary pull-right" %></li>
    <% end %>
  </ul>
  <form class="form-inline float-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</nav>

app/views/shared/_main.html.erb
<% flash.each do |key,msg| %>
	<div class="text-center alert alert-<%=key == 'notice' ? 'success' : 'danger' %>">
		<%= msg %>
	</div>
<% end %>